# Fictional Army - Filtering and Sorting

### Import libraries

In [2]:
import pandas as pd
import numpy as np

### Step 1. This is the data given as a dictionary. Create a dataframe and assign it to a variable called army.

In [3]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, None, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, None, 3, None, 2, None, 2, None, None, 1, 2, None],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

In [9]:
army = pd.DataFrame(raw_data)
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523.0,5,1045,1,1.0,1,4,Arizona
1,Nighthawks,1st,52.0,42,957,5,NaN,0,24,California
2,Nighthawks,2nd,25.0,2,1099,62,3.0,1,31,Texas
3,Nighthawks,2nd,616.0,2,1400,26,NaN,1,2,Florida
4,Dragoons,1st,43.0,4,1592,73,2.0,0,3,Maine
5,Dragoons,1st,234.0,7,1006,37,NaN,1,4,Iowa
6,Dragoons,2nd,523.0,8,987,949,2.0,0,24,Alaska
7,Dragoons,2nd,62.0,3,849,48,NaN,1,31,Washington
8,Scouts,1st,NaN,4,973,48,NaN,0,2,Oregon
9,Scouts,1st,73.0,7,1005,435,1.0,0,3,Wyoming
10,Scouts,2nd,37.0,8,1099,63,2.0,1,2,Louisana
11,Scouts,2nd,35.0,9,1523,345,NaN,1,3,Georgia

In [5]:
army.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   regiment   12 non-null     object
 1   company    12 non-null     object
 2   deaths     11 non-null     float64
 3   battles    12 non-null     int64
 4   size       12 non-null     int64
 5   veterans   12 non-null     int64
 6   readiness  6 non-null      float64
 7   armored    12 non-null     int64
 8   deserters  12 non-null     int64
 9   origin     12 non-null     object
dtypes: float64(2), int64(5), object(3)
memory usage: 1.1+ KB

### Step 2. Check missing values

In [6]:
#Con isnull() vemos los valores de DF que son nulos
army.isnull()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,True,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,True,False,False,False
8,False,False,True,False,False,False,True,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False

In [10]:
#por filas
army(army["readiness"].isnull())

TypeError: 'DataFrame' object is not callable

### Step 3. Drop features, if there are more than 30% missing values.

In [11]:
import math

In [12]:
math.ceil(len(army)*0.7)#redondeamos

9

In [65]:
#dropna nos permite eliminar, en este caso las columnas, que tienen la condicion que se l eimponga para eliminarlas segun la cantidad de NAN
tabla1=army.dropna(axis='columns', thresh=len(army)*0.70)
tabla1

,regiment,company,deaths,battles,size,veterans,armored,deserters,origin
0,Nighthawks,1st,523.0,5,1045,1,1,4,Arizona
1,Nighthawks,1st,52.0,42,957,5,0,24,California
2,Nighthawks,2nd,25.0,2,1099,62,1,31,Texas
3,Nighthawks,2nd,616.0,2,1400,26,1,2,Florida
4,Dragoons,1st,43.0,4,1592,73,0,3,Maine
5,Dragoons,1st,234.0,7,1006,37,1,4,Iowa
6,Dragoons,2nd,523.0,8,987,949,0,24,Alaska
7,Dragoons,2nd,62.0,3,849,48,1,31,Washington
8,Scouts,1st,NaN,4,973,48,0,2,Oregon
9,Scouts,1st,73.0,7,1005,435,0,3,Wyoming
10,Scouts,2nd,37.0,8,1099,63,1,2,Louisana
11,Scouts,2nd,35.0,9,1523,345,1,3,Georgia

### Step 4. Fill missing values with the mean of their regiment.

In [66]:
#Hay que sustituir los valores Nan por la media de, en este caso readiness, cada regimiento
#tendremos que hacer 3 sub DF, uno por regimineto, y hacer la media de la columna para poder sustituir el valor

In [67]:
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523.0,5,1045,1,1.0,1,4,Arizona
1,Nighthawks,1st,52.0,42,957,5,NaN,0,24,California
2,Nighthawks,2nd,25.0,2,1099,62,3.0,1,31,Texas
3,Nighthawks,2nd,616.0,2,1400,26,NaN,1,2,Florida
4,Dragoons,1st,43.0,4,1592,73,2.0,0,3,Maine
5,Dragoons,1st,234.0,7,1006,37,NaN,1,4,Iowa
6,Dragoons,2nd,523.0,8,987,949,2.0,0,24,Alaska
7,Dragoons,2nd,62.0,3,849,48,NaN,1,31,Washington
8,Scouts,1st,NaN,4,973,48,NaN,0,2,Oregon
9,Scouts,1st,73.0,7,1005,435,1.0,0,3,Wyoming
10,Scouts,2nd,37.0,8,1099,63,2.0,1,2,Louisana
11,Scouts,2nd,35.0,9,1523,345,NaN,1,3,Georgia

In [14]:
m1=army[army["regiment"]== "Nighthawks"]["readiness"].mean()

m2=army[army["regiment"]== "Dragoons"]["readiness"].mean()

m3=army[army["regiment"]== "Scouts"]["readiness"].mean()
m3,m2,m1

(np.float64(1.5), np.float64(2.0), np.float64(2.0))

In [18]:
l1=army[army["regiment"]== "Nighthawks"].fillna(m1)
l2=army[army["regiment"]== "Dragoons"].fillna(m2)
l3=army[army["regiment"]== "Scouts"].fillna(m3)
pd.concat([l1,l2,l3],ignore_index=True)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523.0,5,1045,1,1.0,1,4,Arizona
1,Nighthawks,1st,52.0,42,957,5,2.0,0,24,California
2,Nighthawks,2nd,25.0,2,1099,62,3.0,1,31,Texas
3,Nighthawks,2nd,616.0,2,1400,26,2.0,1,2,Florida
4,Dragoons,1st,43.0,4,1592,73,2.0,0,3,Maine
5,Dragoons,1st,234.0,7,1006,37,2.0,1,4,Iowa
6,Dragoons,2nd,523.0,8,987,949,2.0,0,24,Alaska
7,Dragoons,2nd,62.0,3,849,48,2.0,1,31,Washington
8,Scouts,1st,1.5,4,973,48,1.5,0,2,Oregon
9,Scouts,1st,73.0,7,1005,435,1.0,0,3,Wyoming
10,Scouts,2nd,37.0,8,1099,63,2.0,1,2,Louisana
11,Scouts,2nd,35.0,9,1523,345,1.5,1,3,Georgia

In [ ]:
#Lo hacemos para tabla1
tabla1[tabla1["death"]].fillna

### Step 5. Set the 'origin' colum as the index of the dataframe

In [19]:

army1 =army.set_index("origin")#coger una column y la ponemos como indice

army1

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523.0,5,1045,1,1.0,1,4
California,Nighthawks,1st,52.0,42,957,5,NaN,0,24
Texas,Nighthawks,2nd,25.0,2,1099,62,3.0,1,31
Florida,Nighthawks,2nd,616.0,2,1400,26,NaN,1,2
Maine,Dragoons,1st,43.0,4,1592,73,2.0,0,3
Iowa,Dragoons,1st,234.0,7,1006,37,NaN,1,4
Alaska,Dragoons,2nd,523.0,8,987,949,2.0,0,24
Washington,Dragoons,2nd,62.0,3,849,48,NaN,1,31
Oregon,Scouts,1st,NaN,4,973,48,NaN,0,2
Wyoming,Scouts,1st,73.0,7,1005,435,1.0,0,3
Louisana,Scouts,2nd,37.0,8,1099,63,2.0,1,2
Georgia,Scouts,2nd,35.0,9,1523,345,NaN,1,3

### Step 6. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [89]:

army1.loc[["Maine","Alaska"], ["deaths","size","deserters"]]

        deaths  size  deserters
origin
Maine     43.0  1592          3
Alaska   523.0   987         24

### Step 7. Select the rows 3 to 7 and the columns 3 to 6

In [20]:
army1.iloc[2:7,2:6]

         deaths  battles  size  veterans
origin
Texas      25.0        2  1099        62
Florida   616.0        2  1400        26
Maine      43.0        4  1592        73
Iowa      234.0        7  1006        37
Alaska    523.0        8   987       949

### Step 8. Select every row after the fourth row and all columns

In [21]:
army1.iloc[4: ,:]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43.0,4,1592,73,2.0,0,3
Iowa,Dragoons,1st,234.0,7,1006,37,NaN,1,4
Alaska,Dragoons,2nd,523.0,8,987,949,2.0,0,24
Washington,Dragoons,2nd,62.0,3,849,48,NaN,1,31
Oregon,Scouts,1st,NaN,4,973,48,NaN,0,2
Wyoming,Scouts,1st,73.0,7,1005,435,1.0,0,3
Louisana,Scouts,2nd,37.0,8,1099,63,2.0,1,2
Georgia,Scouts,2nd,35.0,9,1523,345,NaN,1,3

### Step 9. Select every row up to the 4th row and all columns

In [22]:
army1.iloc[:4,:]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523.0,5,1045,1,1.0,1,4
California,Nighthawks,1st,52.0,42,957,5,NaN,0,24
Texas,Nighthawks,2nd,25.0,2,1099,62,3.0,1,31
Florida,Nighthawks,2nd,616.0,2,1400,26,NaN,1,2

### Step 10. Select the 3rd column up to the 7th column

In [23]:
army1.iloc[:,2:7]

            deaths  battles  size  veterans  readiness
origin
Arizona      523.0        5  1045         1        1.0
California    52.0       42   957         5        NaN
Texas         25.0        2  1099        62        3.0
Florida      616.0        2  1400        26        NaN
Maine         43.0        4  1592        73        2.0
Iowa         234.0        7  1006        37        NaN
Alaska       523.0        8   987       949        2.0
Washington    62.0        3   849        48        NaN
Oregon         NaN        4   973        48        NaN
Wyoming       73.0        7  1005       435        1.0
Louisana      37.0        8  1099        63        2.0
Georgia       35.0        9  1523       345        NaN

### Step 11. Select rows where df.deaths is greater than 50

In [24]:
army1[army1["deaths"]>50]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523.0,5,1045,1,1.0,1,4
California,Nighthawks,1st,52.0,42,957,5,NaN,0,24
Florida,Nighthawks,2nd,616.0,2,1400,26,NaN,1,2
Iowa,Dragoons,1st,234.0,7,1006,37,NaN,1,4
Alaska,Dragoons,2nd,523.0,8,987,949,2.0,0,24
Washington,Dragoons,2nd,62.0,3,849,48,NaN,1,31
Wyoming,Scouts,1st,73.0,7,1005,435,1.0,0,3

### Step 12. Select rows where df.deaths is greater than 500 or less than 50

In [103]:
army[(army["deaths"]>500) | (army["deaths"]<50)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523.0,5,1045,1,1.0,1,4,Arizona
2,Nighthawks,2nd,25.0,2,1099,62,3.0,1,31,Texas
3,Nighthawks,2nd,616.0,2,1400,26,NaN,1,2,Florida
4,Dragoons,1st,43.0,4,1592,73,2.0,0,3,Maine
6,Dragoons,2nd,523.0,8,987,949,2.0,0,24,Alaska
10,Scouts,2nd,37.0,8,1099,63,2.0,1,2,Louisana
11,Scouts,2nd,35.0,9,1523,345,NaN,1,3,Georgia

### Step 13. Select all the regiments not named "Dragoons"

In [104]:
army[army["regiment"]!= "Dragoons"]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523.0,5,1045,1,1.0,1,4,Arizona
1,Nighthawks,1st,52.0,42,957,5,NaN,0,24,California
2,Nighthawks,2nd,25.0,2,1099,62,3.0,1,31,Texas
3,Nighthawks,2nd,616.0,2,1400,26,NaN,1,2,Florida
8,Scouts,1st,NaN,4,973,48,NaN,0,2,Oregon
9,Scouts,1st,73.0,7,1005,435,1.0,0,3,Wyoming
10,Scouts,2nd,37.0,8,1099,63,2.0,1,2,Louisana
11,Scouts,2nd,35.0,9,1523,345,NaN,1,3,Georgia

### Step 14. Select the rows called Texas and Arizona

In [44]:
army1["Texas","Arizona"]

KeyError: ('Texas', 'Arizona')

### Step 15. Select the third cell in the row named Arizona

In [27]:
army1.loc["Arizona"][2]

C:\Users\UX490U\AppData\Local\Temp\ipykernel_9600\722343901.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  army1.loc["Arizona"][2]

np.float64(523.0)

### Step 16. Select the third cell down in the column named deaths

In [35]:
army["deaths"][3]

np.float64(616.0)