![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

In [2]:
#Escribe el título del proyecto en Markdown
titulo = "Students' Mental Health"
url="https://www.kaggle.com/datasets/ikynahidwin/depression-student-dataset"

### TEMA

In [ ]:
# Describe brevemente el tema del proyecto en Markdown
tema = "El tema del proyecto consiste en un análisis de la salud mental de los estudiantes en base a diversos factores personales y conductuales"

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Deberás tener más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

In [ ]:
# Escribe tu hipótesis principal en Markdown
hipotesis_1 = "La presión academica favorece a una mala salud mental del estudiante"

In [ ]:
# Escribe más hipótesis si las hubiera en Markdown
hipotesis_2 = "La satisfaccion del estudiante con sus resultados no es tan determiante en la salud mental"
hipotesis_3 = "Una mala alimentacion es menos determinante que una buena conducta de sueño en la salud mental"
hipotesis_4 = "El género femenino siente más presion"
hipotesis_5 = "Cuantas más horas de estudio peores hábitos de alimentación y sueño"
hipotesis_6 = "El historial familiar es determinante para padecer depresión"

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [10]:
import pandas as pd
# guarda en variables los datasets y su fuente
df=pd.read_csv("Depression Student Dataset.csv")
df

# df_2 = pd.DataFrame()
# fuente_2 = ""
# df_3 = pd.DataFrame()
# fuente_3 = ""
# df_4 = pd.DataFrame()
# fuente_4 = ""
# df_5 = pd.DataFrame()
# fuente_5 = ""
# ...

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,28,2.0,4.0,7-8 hours,Moderate,Yes,9,2,Yes,No
1,Male,28,4.0,5.0,5-6 hours,Healthy,Yes,7,1,Yes,No
2,Male,25,1.0,3.0,5-6 hours,Unhealthy,Yes,10,4,No,Yes
3,Male,23,1.0,4.0,More than 8 hours,Unhealthy,Yes,7,2,Yes,No
4,Female,31,1.0,5.0,More than 8 hours,Healthy,Yes,4,2,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
497,Male,26,5.0,2.0,More than 8 hours,Unhealthy,No,8,3,No,Yes
498,Male,24,2.0,1.0,Less than 5 hours,Unhealthy,Yes,8,5,No,Yes
499,Female,23,3.0,5.0,5-6 hours,Healthy,No,1,5,Yes,No
500,Male,33,4.0,4.0,More than 8 hours,Healthy,No,8,1,Yes,No
501,Male,18,5.0,3.0,More than 8 hours,Unhealthy,No,6,2,Yes,Yes

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [11]:
# Primer dataset
df.head()

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,28,2.0,4.0,7-8 hours,Moderate,Yes,9,2,Yes,No
1,Male,28,4.0,5.0,5-6 hours,Healthy,Yes,7,1,Yes,No
2,Male,25,1.0,3.0,5-6 hours,Unhealthy,Yes,10,4,No,Yes
3,Male,23,1.0,4.0,More than 8 hours,Unhealthy,Yes,7,2,Yes,No
4,Female,31,1.0,5.0,More than 8 hours,Healthy,Yes,4,2,Yes,No